### ISSUE TITLE
Tagging a release

### ISSUE THREAD

**Issue by kburns** [antequ/fastlinkingnumbers#3]
As an alternative deployment option, I could put together a quick conda-forge package (a cross-platform binary distribution platform) for the code.  If that sounds alright, it would be great to have the latest code tagged with a release / version number on GitHub to keep things in sync.  Would it be possible to add this?

**Comment by antequ** [comment]
Done -- https://github.com/antequ/fastlinkingnumbers/releases/tag/v1.0.0

Hopefully this works. Thanks for looking into this!

**Comment by kburns** [comment]
Thanks!
